export const themeTutorialData = [
  { id: 1, theme: "Utiliser ligne Bleue" },
  {
    id: 2,
    theme: "Utiliser mon téléphone",
    tutorial: [
      {
        id: 1,
        title: "Arrêter et démarrer le téléphone",
        description: "",
        objectif: "Nous allons éteindre et allumer ton téléphone",
        content: [],
        hashtag: [],
        difficulty: "",
        author: "",
      },
      {
        id: 2,
        title: "Utiliser un QR code ",
        description: "",
        objectif: "Apprenons à utiliser un QR code",
        content: [],
        hashtag: [],
        difficulty: "",
        author: "",
      },
      {
        id: 3,
        title: "manipuler écran tactile ",
        description: "",
        objectif: "Savez vous manipuler un écran tactile ?",
        content: [],
        hashtag: [],
        difficulty: "",
        author: "",
      },
      {
        id: 4,
        title: "Téléphoner",
        description: "",
        objectif: "Apprenons à téléphoner",
        content: [],
        hashtag: [],
        difficulty: "",
        author: "",
      },
      {
        id: 5,
        title: "Différence : SMS, mail, message",
        description: "",
        objectif:
          "Savez-vous la différence entre un SMS, un mail et un message ?",
        content: [],
        hashtag: [],
        difficulty: "",
        author: "",
      },
      {
        id: 6,
        title: "Envoyer et recevoir SMS",
        description: "",
        objectif: "Vous allez apprendre à envoyer et recevoir des SMS",
        content: [],
        hashtag: [],
        difficulty: "",
        author: "",
      },
      {
        id: 7,
        title: "Gestion des contacts",
        description: "",
        objectif: "Apprenez à gérer vos contacts",
        content: [],
        hashtag: [],
        difficulty: "",
        author: "",
      },
      {
        id: 8,
        title: "Lexicologie Android",
        description: "",
        objectif:
          "Voici quelques mots que vous allez rencontrer sur votre téléphone",
        content: [],
        hashtag: [],
        difficulty: "",
        author: "",
      },
    ],
  },
  {
    id: 3,
    theme: "Aller sur internet",
  },
  {
    id: 4,
    theme: "Vie Courante",
  },
  {
    id: 5,
    theme: "Me divertir",
  },
  {
    id: 6,
    theme: "Mes mails",
  },
  {
    id: 7,
    theme: "Communiquer",
  },
  {
    id: 8,
    theme: "Utiliser mon téléphone en sécurité",
  },
  {
    id: 9,
    theme: "Se déplacer",
  },
  {
    id: 10,
    theme: "Se faire aider",
  },
];

export default themeTutorialData;
